DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
PRODUCT_ID INTEGER NOT NULL,
PRODUCT_NAME VARCHAR(30),
PRODUCT_PRICE INTEGER,
CREATION_DATE TIMESTAMP NOT NULL
);

ALTER TABLE PRODUCT
ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (ID_PRODUCT)